config/routes.rb
BandcampHelper::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :line_items, only: [:new, :create]
  resources :users, only: [:new, :create, :show]

  root to: 'static_pages#home'

  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete

  match '/signup',  to: 'users#new'

  match '/import', to: 'line_items#new'
  

end

app/models/bandcamp_payment.rb
# == Schema Information
#
# Table name: bandcamp_payments
#
#  id               :integer          not null, primary key
#  payment_date     :datetime
#  amount_collected :decimal(, )
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :integer
#  currency         :string(255)
#

class BandcampPayment < ActiveRecord::Base
  attr_accessible :amount_collected, :payment_date, :currency
  belongs_to :user
end

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id            :integer          not null, primary key
#  purchase_date :datetime
#  name          :string(255)
#  price         :decimal(, )
#  tax           :decimal(, )
#  shipping      :decimal(, )
#  quantity      :integer
#  currency      :string(255)
#  revenue_share :decimal(, )
#  paypal_fee    :decimal(, )
#  paypal_id     :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#

class LineItem < ActiveRecord::Base
  
  attr_accessible :currency, :name, :paypal_fee, :paypal_id, :price, 
                  :purchase_date, :quantity, :revenue_share, :shipping, :tax
                  
  belongs_to :user
                  
  validates :currency, presence: true
  validates :name, presence: true
  validates :paypal_fee, presence: true
  validates :price, presence: true
  validates :purchase_date, presence: true
  validates :quantity, presence: true
  validates :revenue_share, presence: true
  validates :shipping, presence: true
  validates :tax, presence: true

  after_initialize :default_values
  before_save :cleanup_values

  def sub_total
    price * quantity
  end

  def total
    sub_total + tax + shipping
  end

  def net_total
    total - paypal_fee - revenue_share
  end

  private
  
    def default_values
      self.paypal_fee ||= 0.00
      self.price ||= 0.00
      self.quantity ||= 1
      self.revenue_share ||= 0.00
      self.shipping ||= 0.00
      self.tax ||= 0.00
    end
    
    def cleanup_values
      self.paypal_id = '' if self.paypal_id.downcase == 'to bandcamp'
    end
    
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  attr_accessible :email, :name, :password, :password_confirmation
  
  has_many :line_items, dependent: :destroy
  has_many :bandcamp_payments, dependent: :destroy
  
  has_secure_password
  
  validates :name, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  before_save { self.email.downcase! }
  before_save :create_remember_token
  
  def to_s
    name
  end
  
  private
  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  require 'csv'
  
  before_filter :logged_in_user
  
  def new
  end

  def create

    valid_columns = ['order date', 'item name', 'item price', 'quantity',
          'tax', 'shipping', 'assessed revenue share', 'currency', 'paypal fee', 
          'paypal transaction id']
    valid_fields = [:purchase_date, :name, :price, :quantity, :tax, :shipping, 
          :revenue_share, :currency, :paypal_fee, :paypal_id] 

    CSV.parse(params[:filename].read, :headers => true) do |row|
      
      valid_row = row.fields(*valid_columns)
      
      values = Hash[valid_fields.zip(valid_row)]
      values[:purchase_date] = DateTime.strptime(values[:purchase_date], '%m/%d/%y %H:%M%p')
      
      current_user.line_items.create!(values)
      
      if row.field('collected revenue share').to_f > 0
        current_user.bandcamp_payments.create!({ 
          payment_date: values[:purchase_date],
          currency: values[:currency],
          amount_collected: row.field('collected revenue share').to_f
        })   
      end
      
    end
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:username])
    if user && user.authenticate(params[:password])
      login user
      redirect_back_or user
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
  def home
    
    redirect_to current_user if logged_in?
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    
    @user = User.create(params[:user])
    
    if @user.save
      login @user
      redirect_to root_path
    else
      render 'new'
    end
    
  end
  
  def show
    
    @user = current_user
    @items = current_user.line_items
    @payments = current_user.bandcamp_payments
    
    @gross_revenue = 0.00
    @net_revenue = 0.00
    @revenue_share = 0.00
    @revenue_share_collected = 0.00
    
    standard_paypal_fee = Paypal::StandardFee.new
    micro_paypal_fee = Paypal::MicroFee.new
    
    @paypal_fees = {
      actual: 0.00,
      standard: 0.00,
      micro: 0.00
    }
    
    @items.each do |item|
      @gross_revenue += item.total
      @net_revenue += item.net_total
      @revenue_share += item.revenue_share
      @paypal_fees[:actual] += item.paypal_fee
      @paypal_fees[:standard] += standard_paypal_fee.calculate item
      @paypal_fees[:micro] += micro_paypal_fee.calculate item
    end
    
    @payments.each do |p|
      @revenue_share_collected += p.amount_collected
    end
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def logout
    current_user = nil
    cookies.delete(:remember_token)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def logged_in_user
    unless logged_in?
      store_location
      redirect_to login_path, notice: "Please sign in." 
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div id="footer-bar"></div>
  <div id="footer-content">

  </div>
  <div id="copyright">
    <p>&copy; TheTwelve Labs <%= Date.today.year %> | All Rights Reserved</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
  
  <div class="navbar-inner">
    <div class="container">
      
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      
      <%= link_to "Bandcamp Helper", root_path, class: "brand "%>
      
      <div class="nav-collapse collapse">
        <% if logged_in? %>
        <ul class="nav">
          <li>
            <%= link_to "Import", import_path %>
          </li>
        </ul>
        <ul class="nav pull-right">
          <li>
            <%= link_to "Logout", logout_path, method: "delete" %>
          </li>
        </ul>
        <% else %>
        <ul class="nav pull-right">
          <li>
            <%= link_to "Signup", signup_path %>
          </li>
          <li>
            <%= link_to "Login", login_path %>
          </li>
        </ul>
        <% end %>
      </div><!--/.nav-collapse -->
      
    </div>
  </div>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>BandcampHelper</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      
      <%= yield %>
    
      <%= debug(params) if Rails.env.development? %>
        
    </div>
    
    <%= render 'layouts/footer' %>

  </body>
  
</html>

app/views/line_items/create.html.erb
File imported successfully. 

app/views/line_items/new.html.erb
<div class="row">

  <div class="span12">

    <h1>Import Bandcamp Sales</h1>
  
    <%= form_tag(line_items_path, { class: 'form-horizontal', method: 'post', multipart: true } ) do %>
      <div class="control-group">
        <%= label_tag 'filename', 'File', class: "control-label" %> 
        <div class="controls">
          <%= file_field_tag "filename" %>
        </div>
      </div>
    
      <div class="form-actions">
        <%= submit_tag "Import", class: "btn btn-primary" %>
        <a href="<%= root_path %>" class="btn">Cancel</a>
      </div>
    
    <% end %>
    
  </div>
  
</div>

app/views/shared/_form_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login.html.erb
<%= form_tag(sessions_path, class: 'form-signin') do %>
  <h2 class="form-signin-heading">Please sign in</h2>
  <%= text_field_tag :username, '', class: 'input-block-level', placeholder: 'Email Address' %>
  <%= password_field_tag :password, '', class: 'input-block-level', placeholder: 'Password' %>
  <%= label_tag 'remember-me', 
                check_box_tag('remember-me', 1, false) + ' Remember me', 
                class: 'checkbox' %>
  <%= submit_tag "Sign in", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_login_modal.html.erb
<div class="modal hide fade" id="login">
  <div class="modal-body">
    <%= render "shared/login" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row" id="signup">

  <div class="span8 offset2">

    <%= form_for @user, html: { class: "form-horizontal" } do |f| %>
    
      <%= render 'shared/form_messages', object: f.object %>
    
      <div class="control-group">
        <%= f.label :name, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :name, class: "input-xlarge" %>
        </div>
      </div>
        
      <div class="control-group">
        <%= f.label :email, "Email Address", class: "control-label" %>
        <div class="controls">
          <%= f.text_field :email, class: "input-xlarge" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :password, class: "control-label" %>
        <div class="controls">
          <%= f.password_field :password, class: "input-xlarge" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
        <div class="controls">
          <%= f.password_field :password_confirmation, class: "input-xlarge" %>
        </div>
      </div>
      
      <div class="form-actions">
        <%= f.submit "Create your Account", :class => "btn btn-primary" %>
        <%= link_to 'Cancel', root_path, class: "btn" %>
      </div>
      
    <% end %>
    
  </div>

</div>

app/views/users/show.html.erb
<div class="row">
  
  <h1>Bandcamp Account: <%= @user %></h1>
  
  <div class="span10">
    Total Gross Revenue: $<%= sprintf "%.2f", @gross_revenue %>
  </div>

  <div class="span10">
    Total Net Revenue: $<%= sprintf "%.2f", @net_revenue %>
  </div>
  
  <div class="span10">
    Total Revenue Share Assessed: $<%= sprintf "%.2f", @revenue_share %>
  </div>

  <div class="span10">
    Total Revenue Share Collected $<%= sprintf "%.2f", @revenue_share_collected %>
  </div>

  <div class="span10">
    Total Paypal Fees: $<%= sprintf "%.2f", @paypal_fees[:actual] %>
  </div>

  <div class="span10">
    Paypal Fee Estimations
    <ul>
      <li>Using Standard Fee: $<%= sprintf "%.2f", @paypal_fees[:standard] %></li>
      <li>Using Micro Fee: $<%= sprintf "%.2f", @paypal_fees[:micro] %></li>
    </ul>
  </div>
  
</div>